name: ESLint & Build Test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'

      - name: Install Dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Lint Code
        run: npm run lint
        working-directory: ./frontend

      - name: Build Test
        run: npm run build
        working-directory: ./frontend
